### ISSUE TITLE
Problem with TabControl' size since 11.0 version

### ISSUE THREAD

**Issue by morerave** [flarive/Neumorphism.Avalonia#35]
since the update, the tabcontrol have limited size.
Need to resize the Tabcontrol
![TabControlWithoutResize](https://github.com/flarive/Neumorphism.Avalonia/assets/56629528/5109403f-a6b5-4016-a1e2-1ca778f8bf03)

**Comment by flarive** [comment]
Hum... strange...
I would need a sample repro please to have a look...
Could you share your repo ?

**Comment by morerave** [comment]
yes of course : 
https://github.com/morerave/AvaloniaApplicationTestList

**Comment by flarive** [comment]
Hello,

Bug fixed.
Now TabControl should be able to stretch correctly to fit your window size horizontally and vertically.
Insert your TabControl into a Grid, not into a StackPanel because StackPanel can't stretch children.

I have added a new "Stretchable TabControl" demo in the demo project.

https://github.com/flarive/Neumorphism.Avalonia/releases/tag/0.11.1

Tell me if iy's ok for you...

**Comment by morerave** [comment]
HI, I tried it. it's work but I don't have to use a Grid. it's work with a StackPanel

**Comment by morerave** [comment]
corrected in version 0.11.1
